# Generated by Django 4.2 on 2024-04-01 14:18

import News.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=999, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to=News.models.news_picture_path)),
            ],
        ),
    ]
