# Generated by Django 4.2 on 2024-05-12 14:31

import Users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_profile_pictures',
            field=models.ImageField(blank=True, default='D:\\Work\\Python\\Flex\\FlexBOOST\\FlexBook\\static\\Server_images\\default_profile_image.webp', null=True, upload_to=Users.models.user_profile_picture_path),
        ),
    ]
