# Generated by Django 4.2 on 2024-05-12 14:27

import Games.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(default='None', max_length=50)),
                ('game_img', models.ImageField(blank=True, default='D:\\pythonProject\\ProjectDjango\\FlexBook\\static\\Server_images\\sticker.webp', null=True, upload_to=Games.models.game_profile_picture_path)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_value', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('rank_img', models.ImageField(blank=True, default='D:\\pythonProject\\ProjectDjango\\FlexBook\\static\\Server_images\\sticker.webp', null=True, upload_to=Games.models.game_rank_picture_path)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Games.game')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GameRankAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_rank', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='from_rank', to='Games.rank')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Games.game')),
                ('to_rank', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='to_rank', to='Games.rank')),
            ],
        ),
    ]
