# Generated by Django 4.2 on 2024-04-01 14:18

import Games.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(default='None', max_length=50)),
                ('game_img', models.ImageField(blank=True, default='D:\\pythonProject\\ProjectDjango\\FlexBook\\static\\Server_images\\sticker.webp', null=True, upload_to=Games.models.game_profile_picture_path)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_value', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('rank_img', models.ImageField(blank=True, default='D:\\pythonProject\\ProjectDjango\\FlexBook\\static\\Server_images\\sticker.webp', null=True, upload_to=Games.models.game_rank_picture_path)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Games.game')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GameRankAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id_from', models.PositiveIntegerField(default=0)),
                ('object_id_to', models.PositiveIntegerField(default=0)),
                ('content_type_from', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='from_rank_content_type', to='contenttypes.contenttype')),
                ('content_type_to', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='to_rank_content_type', to='contenttypes.contenttype')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Games.game')),
            ],
        ),
    ]
