# Generated by Django 4.2 on 2024-04-01 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamerankassociation',
            name='content_type_from',
        ),
        migrations.RemoveField(
            model_name='gamerankassociation',
            name='content_type_to',
        ),
        migrations.RemoveField(
            model_name='gamerankassociation',
            name='object_id_from',
        ),
        migrations.RemoveField(
            model_name='gamerankassociation',
            name='object_id_to',
        ),
        migrations.AddField(
            model_name='gamerankassociation',
            name='from_rank',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='from_rank', to='Games.rank'),
        ),
        migrations.AddField(
            model_name='gamerankassociation',
            name='to_rank',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='to_rank', to='Games.rank'),
        ),
    ]
